(* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- *)

unit example;

{$mode objfpc}{$H+}

{$define example_FUNCTION_WRAPPER}
{$define example_CLASS_WRAPPER}

interface

uses 

// interface_uses


     Classes,
     SysUtils;


// interface_uses



// interface_type_begin 


//pasraw_intf.f

type
  PSimple = pointer;

// interface_type_end 



// interface_functions

  function New_Simple( ):PSimple; stdcall;

  procedure Delete_Simple( self:PSimple ); stdcall;

  procedure Simple_move( self:PSimple;  dx, dy:Double ); stdcall;

{$ifdef example_FUNCTION_WRAPPER}

// interface_functions_wrapper

  procedure Simple_x_set( self:PSimple; x:Double ); stdcall;

  function Simple_x_get( self:PSimple ):Double; stdcall;

  procedure Simple_y_set( self:PSimple; y:Double ); stdcall;

  function Simple_y_get( self:PSimple ):Double; stdcall;

{$endif} //example_FUNCTION_WRAPPER

{$ifdef example_CLASS_WRAPPER}

type

  Simple = class (TObject)

    private
      FCObjPtr : PSimple;
      FOwnCObjPtr : boolean;
    
    protected
      procedure SetCObjPtr(Value : PSimple);
    
    public

    constructor Create ();overload; 

    procedure SetX ( value: Double);

    function GetX (): Double;

 public                  
	property X : Double read GetX write SetX;

    procedure SetY ( value: Double);

    function GetY (): Double;

 public                  
	property Y : Double read GetY write SetY;

    procedure move ( dx: Double;  dy: Double);

    destructor Destroy; override;

  //various other methods
  
  public  
    property CObjPtr : PSimple read FCObjPtr write SetCObjPtr;
    property OwnCObjPtr : boolean read FOwnCObjPtr  write FOwnCObjPtr ;
  //proxy class methods
  end;
{$endif} //example_CLASS_WRAPPER
// Output a Pascal type wrapper class for each SWIG type
implementation


// implementation_type_begin



// implementation_uses

// implementation_type_end

// implementation_functions

{$IFDEF LINUX}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF MSWINDOWS}
{$linklib example.dll}
const __WRAPDLLNAME= 'example_wrap.dll';
{$ENDIF}

{$IFDEF HAIKU}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF QTOPIA}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF DARWIN}
{$linklib example}
const __WRAPDLLNAME= '';
{$LINKFRAMEWORK example}
{$ENDIF}
 


  function New_Simple( ):PSimple; stdcall; external __WRAPDLLNAME name 'new_Simple';

  procedure Delete_Simple( self:PSimple ); stdcall; external __WRAPDLLNAME name 'delete_Simple';

  procedure Simple_move( self:PSimple;  dx, dy:Double ); stdcall; external __WRAPDLLNAME name 'Simple_move';

{$ifdef example_FUNCTION_WRAPPER}

// implementation_functions_wrapper

  procedure Simple_x_set( self:PSimple; x:Double ); stdcall; external __WRAPDLLNAME name 'Simple_x_set';

  function Simple_x_get( self:PSimple ):Double; stdcall; external __WRAPDLLNAME name 'Simple_x_get';

  procedure Simple_y_set( self:PSimple; y:Double ); stdcall; external __WRAPDLLNAME name 'Simple_y_set';

  function Simple_y_get( self:PSimple ):Double; stdcall; external __WRAPDLLNAME name 'Simple_y_get';

{$endif} //example_FUNCTION_WRAPPER

{$ifdef example_CLASS_WRAPPER}

constructor Simple.Create ();begin
  inherited Create;
  FOwnCObjPtr := true;
   FCObjPtr := example.New_Simple();
end;

procedure Simple.SetX ( value: Double);begin
  assert(FCObjPtr <> nil);
 example.Simple_x_set(Self.FCObjPtr, value);
end;

function Simple.GetX (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Simple_x_get(Self.FCObjPtr) ;
end;

procedure Simple.SetY ( value: Double);begin
  assert(FCObjPtr <> nil);
 example.Simple_y_set(Self.FCObjPtr, value);
end;

function Simple.GetY (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Simple_y_get(Self.FCObjPtr) ;
end;

procedure Simple.move ( dx: Double;  dy: Double);begin
  assert(FCObjPtr <> nil);
 example.Simple_move(Self.FCObjPtr, dx, dy);
end;

destructor Simple.Destroy; 
begin   
  if (FCObjPtr <> nil) and  FOwnCObjPtr then begin 
    example.delete_Simple(FCObjPtr);
    FOwnCObjPtr := false;
  end;
  FCObjPtr := nil; 
  inherited Destroy;
end;

procedure Simple.SetCObjPtr(Value : PSimple);
    begin
      if (Value <> FCObjPtr) then begin
      if (FCObjPtr <> nil) and  FOwnCObjPtr then begin 
        example.delete_Simple(FCObjPtr);
      end;
      FCObjPtr := Value;
      end;
    end;
  

{$endif} //example_CLASS_WRAPPER

initialization


// constant_initialization

// initialization


finalization

// finalization


end.
