(* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- *)

unit example;

{$mode objfpc}{$H+}

{$define example_FUNCTION_WRAPPER}
{$define example_CLASS_WRAPPER}

interface

uses 

// interface_uses


     Classes,
     SysUtils;


// interface_uses



// interface_type_begin 


//pasraw_intf.f

type
  PShape = pointer;

type
  PCircle = pointer;

type
  PSquare = pointer;

// interface_type_end 



// interface_functions

  procedure Delete_Shape( self:PShape ); stdcall;

  procedure Shape_testbool( self:PShape; b:LongBool ); stdcall;

  procedure Shape_move( self:PShape;  dx, dy:Double ); stdcall;

  function Shape_area( self:PShape ):Double; stdcall;

  function Shape_perimeter( self:PShape ):Double; stdcall;

  procedure Shape_nshapes_set(Shape_nshapes:Integer ); stdcall;

  function Shape_nshapes_get( ):Integer; stdcall;

  function New_Circle(r:Double ):PCircle; stdcall;

  function Circle_area( self:PCircle ):Double; stdcall;

  function Circle_perimeter( self:PCircle ):Double; stdcall;

  procedure Delete_Circle( self:PCircle ); stdcall;

  function New_Square(w:Double ):PSquare; stdcall;

  function Square_area( self:PSquare ):Double; stdcall;

  function Square_perimeter( self:PSquare ):Double; stdcall;

  procedure Delete_Square( self:PSquare ); stdcall;

{$ifdef example_FUNCTION_WRAPPER}

// interface_functions_wrapper

  procedure Shape_x_set( self:PShape; x:Double ); stdcall;

  function Shape_x_get( self:PShape ):Double; stdcall;

  procedure Shape_y_set( self:PShape; y:Double ); stdcall;

  function Shape_y_get( self:PShape ):Double; stdcall;

{$endif} //example_FUNCTION_WRAPPER

{$ifdef example_CLASS_WRAPPER}

type

  Shape = class (TObject)

    private
      FCObjPtr : PShape;
      FOwnCObjPtr : boolean;
    
    protected
      procedure SetCObjPtr(Value : PShape);
    
    public

    constructor Create; overload; virtual;
    constructor Create(CObjPtr:PShape; OwnObj:boolean); overload; 

    procedure SetX ( value: Double);

    function GetX (): Double;

 public                  
	property X : Double read GetX write SetX;

    procedure SetY ( value: Double);

    function GetY (): Double;

 public                  
	property Y : Double read GetY write SetY;

    procedure testbool ( b: LongBool);

    procedure move ( dx: Double;  dy: Double);

    function area (): Double;virtual; 

    function perimeter (): Double;virtual; 

    class procedure SetNshapes ( Shape_nshapes: Integer);

    class function GetNshapes (): Integer;

    destructor Destroy; override;

  //various other methods
  
  public  
    property CObjPtr : PShape read FCObjPtr write SetCObjPtr;
    property OwnCObjPtr : boolean read FOwnCObjPtr  write FOwnCObjPtr ;
  //proxy class methods
  end;
  Circle = class (Shape) 
    public

    constructor Create ( r: Double);overload; 

    function area (): Double;override; 

    function perimeter (): Double;override; 

    destructor Destroy; override;

  //various other methods
  //proxy class methods
  end;
  Square = class (Shape) 
    public

    constructor Create ( w: Double);overload; 

    function area (): Double;override; 

    function perimeter (): Double;override; 

    destructor Destroy; override;

  //various other methods
  //proxy class methods
  end;
{$endif} //example_CLASS_WRAPPER
// Output a Pascal type wrapper class for each SWIG type
implementation


// implementation_type_begin



// implementation_uses

// implementation_type_end

// implementation_functions

{$IFDEF LINUX}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF MSWINDOWS}
{$linklib example.dll}
const __WRAPDLLNAME= 'example_wrap.dll';
{$ENDIF}

{$IFDEF HAIKU}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF QTOPIA}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF DARWIN}
{$linklib example}
const __WRAPDLLNAME= '';
{$LINKFRAMEWORK example}
{$ENDIF}
 


  procedure Delete_Shape( self:PShape ); stdcall; external __WRAPDLLNAME name 'delete_Shape';

  procedure Shape_testbool( self:PShape; b:LongBool ); stdcall; external __WRAPDLLNAME name 'Shape_testbool';

  procedure Shape_move( self:PShape;  dx, dy:Double ); stdcall; external __WRAPDLLNAME name 'Shape_move';

  function Shape_area( self:PShape ):Double; stdcall; external __WRAPDLLNAME name 'Shape_area';

  function Shape_perimeter( self:PShape ):Double; stdcall; external __WRAPDLLNAME name 'Shape_perimeter';

  procedure Shape_nshapes_set(Shape_nshapes:Integer ); stdcall; external __WRAPDLLNAME name 'Shape_nshapes_set';

  function Shape_nshapes_get( ):Integer; stdcall; external __WRAPDLLNAME name 'Shape_nshapes_get';

  function New_Circle(r:Double ):PCircle; stdcall; external __WRAPDLLNAME name 'new_Circle';

  function Circle_area( self:PCircle ):Double; stdcall; external __WRAPDLLNAME name 'Circle_area';

  function Circle_perimeter( self:PCircle ):Double; stdcall; external __WRAPDLLNAME name 'Circle_perimeter';

  procedure Delete_Circle( self:PCircle ); stdcall; external __WRAPDLLNAME name 'delete_Circle';

  function New_Square(w:Double ):PSquare; stdcall; external __WRAPDLLNAME name 'new_Square';

  function Square_area( self:PSquare ):Double; stdcall; external __WRAPDLLNAME name 'Square_area';

  function Square_perimeter( self:PSquare ):Double; stdcall; external __WRAPDLLNAME name 'Square_perimeter';

  procedure Delete_Square( self:PSquare ); stdcall; external __WRAPDLLNAME name 'delete_Square';

{$ifdef example_FUNCTION_WRAPPER}

// implementation_functions_wrapper

  procedure Shape_x_set( self:PShape; x:Double ); stdcall; external __WRAPDLLNAME name 'Shape_x_set';

  function Shape_x_get( self:PShape ):Double; stdcall; external __WRAPDLLNAME name 'Shape_x_get';

  procedure Shape_y_set( self:PShape; y:Double ); stdcall; external __WRAPDLLNAME name 'Shape_y_set';

  function Shape_y_get( self:PShape ):Double; stdcall; external __WRAPDLLNAME name 'Shape_y_get';

{$endif} //example_FUNCTION_WRAPPER

{$ifdef example_CLASS_WRAPPER}

procedure Shape.SetX ( value: Double);begin
  assert(FCObjPtr <> nil);
 example.Shape_x_set(Self.FCObjPtr, value);
end;

function Shape.GetX (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Shape_x_get(Self.FCObjPtr) ;
end;

procedure Shape.SetY ( value: Double);begin
  assert(FCObjPtr <> nil);
 example.Shape_y_set(Self.FCObjPtr, value);
end;

function Shape.GetY (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Shape_y_get(Self.FCObjPtr) ;
end;

procedure Shape.testbool ( b: LongBool);begin
  assert(FCObjPtr <> nil);
 example.Shape_testbool(Self.FCObjPtr, b  );
end;

procedure Shape.move ( dx: Double;  dy: Double);begin
  assert(FCObjPtr <> nil);
 example.Shape_move(Self.FCObjPtr, dx, dy);
end;

function Shape.area (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Shape_area(Self.FCObjPtr) ;
end;

function Shape.perimeter (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Shape_perimeter(Self.FCObjPtr) ;
end;

class procedure Shape.SetNshapes ( Shape_nshapes: Integer);begin

 example.Shape_nshapes_set(Shape_nshapes);
end;

class function Shape.GetNshapes (): Integer;begin

  Result := example.Shape_nshapes_get() ;
end;

constructor Shape.Create; 
begin
  inherited Create;
  FCObjPtr := nil;
  FOwnCObjPtr := true
end;

constructor Shape.Create(CObjPtr:PShape; OwnObj:boolean); 
begin
  inherited Create;
  FCObjPtr := CObjPtr;
  FOwnCObjPtr := OwnObj
end;


destructor Shape.Destroy; 
begin   
  if (FCObjPtr <> nil) and  FOwnCObjPtr then begin 
    example.delete_Shape(FCObjPtr);
    FOwnCObjPtr := false;
  end;
  FCObjPtr := nil; 
  inherited Destroy;
end;

procedure Shape.SetCObjPtr(Value : PShape);
    begin
      if (Value <> FCObjPtr) then begin
      if (FCObjPtr <> nil) and  FOwnCObjPtr then begin 
        example.delete_Shape(FCObjPtr);
      end;
      FCObjPtr := Value;
      end;
    end;
  

constructor Circle.Create ( r: Double);begin
  inherited Create;
  FOwnCObjPtr := true;
   FCObjPtr := example.New_Circle(r);
end;

function Circle.area (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Circle_area(Self.FCObjPtr) ;
end;

function Circle.perimeter (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Circle_perimeter(Self.FCObjPtr) ;
end;

    destructor Circle.Destroy;
    begin   
      if (FCObjPtr <> nil) and FOwnCObjPtr then begin 
        example.delete_Circle(FCObjPtr);
        FOwnCObjPtr := false;
      end;  
      FCObjPtr := nil; 
      inherited Destroy;
    end;
  

constructor Square.Create ( w: Double);begin
  inherited Create;
  FOwnCObjPtr := true;
   FCObjPtr := example.New_Square(w);
end;

function Square.area (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Square_area(Self.FCObjPtr) ;
end;

function Square.perimeter (): Double;begin
  assert(FCObjPtr <> nil);
  Result := example.Square_perimeter(Self.FCObjPtr) ;
end;

    destructor Square.Destroy;
    begin   
      if (FCObjPtr <> nil) and FOwnCObjPtr then begin 
        example.delete_Square(FCObjPtr);
        FOwnCObjPtr := false;
      end;  
      FCObjPtr := nil; 
      inherited Destroy;
    end;
  

{$endif} //example_CLASS_WRAPPER

initialization


// constant_initialization

// initialization


finalization

// finalization


end.
