/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class QAtomicAdditiveType_int {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QAtomicAdditiveType_int(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QAtomicAdditiveType_int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        structmplJNI.delete_QAtomicAdditiveType_int(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QAtomicAdditiveType_int() {
    this(structmplJNI.new_QAtomicAdditiveType_int(), true);
  }

  public final static int AddScaleS = structmplJNI.QAtomicAdditiveType_int_AddScaleS_get();
}
