/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class QStr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QStr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QStr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        structmplJNI.delete_QStr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QStr() {
    this(structmplJNI.new_QStr(), true);
  }

  public final static int Constant = structmplJNI.QStr_Constant_get();
}
