/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class structmplJNI {
  public final static native int QStr_Constant_get();
  public final static native long new_QStr();
  public final static native void delete_QStr(long jarg1);
  public final static native int QAtomicAdditiveType_int_AddScaleS_get();
  public final static native long new_QAtomicAdditiveType_int();
  public final static native void delete_QAtomicAdditiveType_int(long jarg1);
}
