/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class QStruct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        struct_constJNI.delete_QStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QStruct() {
    this(struct_constJNI.new_QStruct(), true);
  }

  public final static int Constant = struct_constJNI.QStruct_Constant_get();
}
