/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class struct_constJNI {
  public final static native int QStruct_Constant_get();
  public final static native long new_QStruct();
  public final static native void delete_QStruct(long jarg1);
}
