(* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- *)

unit struct_const;

{$mode objfpc}{$H+}

{$define struct_const_FUNCTION_WRAPPER}
{$define struct_const_CLASS_WRAPPER}

interface



// interface_uses



// interface_type_begin 


//pasraw_intf.f

// interface_type_end 



// interface_functions

{$ifdef struct_const_FUNCTION_WRAPPER}

// interface_functions_wrapper

{$endif} //struct_const_FUNCTION_WRAPPER

{$ifdef struct_const_CLASS_WRAPPER}

{$endif} //struct_const_CLASS_WRAPPER
// Output a Pascal type wrapper class for each SWIG type
implementation


// implementation_type_begin



// implementation_uses

// implementation_type_end

// implementation_functions

{$IFDEF LINUX}
{$linklib libstruct_const.so}
const __WRAPDLLNAME= 'libstruct_const_wrap.so';
{$ENDIF}

{$IFDEF MSWINDOWS}
{$linklib struct_const.dll}
const __WRAPDLLNAME= 'struct_const_wrap.dll';
{$ENDIF}

{$IFDEF HAIKU}
{$linklib libstruct_const.so}
const __WRAPDLLNAME= 'libstruct_const_wrap.so';
{$ENDIF}

{$IFDEF QTOPIA}
{$linklib libstruct_const.so}
const __WRAPDLLNAME= 'libstruct_const_wrap.so';
{$ENDIF}

{$IFDEF DARWIN}
{$linklib struct_const}
const __WRAPDLLNAME= '';
{$LINKFRAMEWORK struct_const}
{$ENDIF}
 


{$ifdef struct_const_FUNCTION_WRAPPER}

// implementation_functions_wrapper

{$endif} //struct_const_FUNCTION_WRAPPER

{$ifdef struct_const_CLASS_WRAPPER}

{$endif} //struct_const_CLASS_WRAPPER

initialization


// constant_initialization

// initialization


finalization

// finalization


end.
