(* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- *)

unit example;

{$mode objfpc}{$H+}

{$define example_FUNCTION_WRAPPER}
{$define example_CLASS_WRAPPER}

interface



// interface_uses



// interface_type_begin 


//pasraw_intf.f

type

   color = type integer; // it is an enum
   Pcolor=^color;

const
   color_RED = 0 ;
   color_BLUE = 1 ;
   color_GREEN = 2 ;

type

   speed = type integer; // it is an enum
   Pspeed=^speed;

const
   Foo_speed_IMPULSE = 10 ;
   Foo_speed_WARP = 20 ;
   Foo_speed_LUDICROUS = 30 ;

type
  PFoo = pointer;

// interface_type_end 



// interface_functions

  function New_Foo( ):PFoo; stdcall;

  procedure Foo_enum_test( self:PFoo; s:integer ); stdcall;

  procedure Delete_Foo( self:PFoo ); stdcall;

  procedure Enum_test( c, s:integer ); stdcall;

{$ifdef example_FUNCTION_WRAPPER}

// interface_functions_wrapper

{$endif} //example_FUNCTION_WRAPPER

{$ifdef example_CLASS_WRAPPER}

type

  Foo = class (TObject)

    private
      FCObjPtr : PFoo;
      FOwnCObjPtr : boolean;
    
    protected
      procedure SetCObjPtr(Value : PFoo);
    
    public

    constructor Create ();overload; 

    procedure enum_test ( s: integer);

    destructor Destroy; override;

  //various other methods
  
  public  
    property CObjPtr : PFoo read FCObjPtr write SetCObjPtr;
    property OwnCObjPtr : boolean read FOwnCObjPtr  write FOwnCObjPtr ;
  //proxy class methods
  end;
{$endif} //example_CLASS_WRAPPER
// Output a Pascal type wrapper class for each SWIG type
implementation


// implementation_type_begin



// implementation_uses

// implementation_type_end

// implementation_functions

{$IFDEF LINUX}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF MSWINDOWS}
{$linklib example.dll}
const __WRAPDLLNAME= 'example_wrap.dll';
{$ENDIF}

{$IFDEF HAIKU}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF QTOPIA}
{$linklib libexample.so}
const __WRAPDLLNAME= 'libexample_wrap.so';
{$ENDIF}

{$IFDEF DARWIN}
{$linklib example}
const __WRAPDLLNAME= '';
{$LINKFRAMEWORK example}
{$ENDIF}
 


  function New_Foo( ):PFoo; stdcall; external __WRAPDLLNAME name 'new_Foo';

  procedure Foo_enum_test( self:PFoo; s:integer ); stdcall; external __WRAPDLLNAME name 'Foo_enum_test';

  procedure Delete_Foo( self:PFoo ); stdcall; external __WRAPDLLNAME name 'delete_Foo';

  procedure Enum_test( c, s:integer ); stdcall; external __WRAPDLLNAME name '__enum_test';

{$ifdef example_FUNCTION_WRAPPER}

// implementation_functions_wrapper

{$endif} //example_FUNCTION_WRAPPER

{$ifdef example_CLASS_WRAPPER}

constructor Foo.Create ();begin
  inherited Create;
  FOwnCObjPtr := true;
   FCObjPtr := example.New_Foo();
end;

procedure Foo.enum_test ( s: integer);begin
  assert(FCObjPtr <> nil);
 example.Foo_enum_test(Self.FCObjPtr, s);
end;

destructor Foo.Destroy; 
begin   
  if (FCObjPtr <> nil) and  FOwnCObjPtr then begin 
    example.delete_Foo(FCObjPtr);
    FOwnCObjPtr := false;
  end;
  FCObjPtr := nil; 
  inherited Destroy;
end;

procedure Foo.SetCObjPtr(Value : PFoo);
    begin
      if (Value <> FCObjPtr) then begin
      if (FCObjPtr <> nil) and  FOwnCObjPtr then begin 
        example.delete_Foo(FCObjPtr);
      end;
      FCObjPtr := Value;
      end;
    end;
  

{$endif} //example_CLASS_WRAPPER

initialization


// constant_initialization

// initialization


finalization

// finalization


end.
